# Generated by Django 2.0.6 on 2018-06-15 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('patente', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
                ('fechaVencimiento', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.PositiveIntegerField()),
                ('dv', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('k', 'k')], max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fechaVencimiento', models.DateField()),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConductorBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.Bus')),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.Conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.PositiveIntegerField()),
                ('dv', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('k', 'k')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('gps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contend.Gps')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('latInicial', models.FloatField()),
                ('lngInicial', models.FloatField()),
                ('latFinal', models.FloatField()),
                ('lngFinal', models.FloatField()),
                ('habilitado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contend.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contend.Empresa'),
        ),
        migrations.AddField(
            model_name='calle',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contend.Ruta'),
        ),
        migrations.AddField(
            model_name='busruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contend.Ruta'),
        ),
        migrations.AddField(
            model_name='bus',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contend.Empresa'),
        ),
        migrations.AddField(
            model_name='bus',
            name='serialGps',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.Gps'),
        ),
    ]
