# Generated by Django 2.0.6 on 2018-06-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='lat',
            field=models.FloatField(default=-33.44889),
        ),
        migrations.AlterField(
            model_name='gps',
            name='lng',
            field=models.FloatField(default=-70.669265),
        ),
    ]
