# Generated by Django 2.0.6 on 2018-06-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0003_auto_20180608_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contend.Empresa'),
            preserve_default=False,
        ),
    ]
