# Generated by Django 2.0.6 on 2018-06-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0004_bus_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='conductorBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conductorbus',
            name='bus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.Bus'),
        ),
        migrations.AddField(
            model_name='conductorbus',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contend.Conductor'),
        ),
    ]
