# Generated by Django 2.0.6 on 2018-06-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0006_auto_20180608_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='habilidato',
            field=models.BooleanField(default=True),
        ),
    ]
