# Generated by Django 2.0.6 on 2018-06-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0007_bus_habilidato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='habilidato',
            new_name='habilitado',
        ),
    ]
