# Generated by Django 2.0.6 on 2018-06-08 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0008_auto_20180608_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.Bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contend.Ruta')),
            ],
        ),
    ]
