# Generated by Django 2.0.6 on 2018-06-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0009_busruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
