# Generated by Django 2.0.6 on 2018-06-11 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0010_conductor_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductorbus',
            name='conductor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.Conductor'),
        ),
    ]
