# Generated by Django 2.0.6 on 2018-06-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0012_bus_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruta',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
