# Generated by Django 2.0.6 on 2018-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0014_auto_20180612_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calle',
            old_name='latFinal',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='calle',
            old_name='latInicial',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='calle',
            name='lngFinal',
        ),
        migrations.RemoveField(
            model_name='calle',
            name='lngInicial',
        ),
        migrations.RemoveField(
            model_name='calle',
            name='nombre',
        ),
    ]
